import { ProductTemplate } from './product-template';

export const ALLBUGGYS: ProductTemplate[] = [
    {id: 101,
    sectionId: 1,
    type: 'buggy',
    model: 'disneyXS',
    h1: 'Прогулочная коляска-"книжка" Easywalker Disney XS Mickey Ornament',
    price: 8850,
    sex: 'boy',
    img1: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Разработка дизайна и брендирование от компании Disney.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: '2 дополнительные подножки для комфорта малыша, он без усилий сможет со временем сам садиться и спускаться с коляски.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 102,
    sectionId: 1,
    type: 'buggy',
    model: 'disneyXS',
    h1: 'Прогулочная коляска-"книжка" Easywalker Disney XS Minnie Ornament',
    price: 8850,
    sex: 'girl',
    img1: '../../assets/img/img_product_disneyXs/Minnie.jpg',
    img2: '../../assets/img/img_product_disneyXs/Minnie.jpg',
    img3: '../../assets/img/img_product_disneyXs/Minnie.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Разработка дизайна и брендирование от компании Disney.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: '2 дополнительные подножки для комфорта малыша, он без усилий сможет со временем сам садиться и спускаться с коляски.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 103,
    sectionId: 1,
    type: 'buggy',
    model: 'disneyXS',
    h1: 'Прогулочная коляска-"книжка" Easywalker Disney XS Mickey Diamond',
    price: 8850,
    sex: 'all',
    img1: '../../assets/img/img_product_disneyXs/Diamond.jpg',
    img2: '../../assets/img/img_product_disneyXs/Diamond.jpg',
    img3: '../../assets/img/img_product_disneyXs/Diamond.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Разработка дизайна и брендирование от компании Disney.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: '2 дополнительные подножки для комфорта малыша, он без усилий сможет со временем сам садиться и спускаться с коляски.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 201,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS Union Jack Classic',
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/UJ_Classic.jpg',
    img2: '../../assets/img/img_product_miniXs/UJ_Classic.jpg',
    img3: '../../assets/img/img_product_miniXs/UJ_Classic.jpg',
    price: 8670,
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн в стиле MINI copper от BMW.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Мягкий матрасик для комфортного сна ребёнка с боковой поддержкой спины и ног.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 202,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS Union Jack Vintage',
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/UJ_Vintage.jpg',
    img2: '../../assets/img/img_product_miniXs/UJ_Vintage.jpg',
    img3: '../../assets/img/img_product_miniXs/UJ_Vintage.jpg',
    price: 8670,
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн в стиле MINI copper от BMW.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Мягкий матрасик для комфортного сна ребёнка с боковой поддержкой спины и ног.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 203,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS LXRY Black',
    price: 8850,
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/LXRY_Black.jpg',
    img2: '../../assets/img/img_product_miniXs/LXRY_Black.jpg',
    img3: '../../assets/img/img_product_miniXs/LXRY_Black.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн в стиле MINI copper от BMW.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Мягкий матрасик для комфортного сна ребёнка с боковой поддержкой спины и ног.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 204,
    sectionId: 2,
    type: 'buggy',
    model: 'miniXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker MINI Buggy XS Union Jack Vintage B&W',
    price: 8850,
    sex: 'all',
    img1: '../../assets/img/img_product_miniXs/UJ_BW.jpg',
    img2: '../../assets/img/img_product_miniXs/UJ_BW.jpg',
    img3: '../../assets/img/img_product_miniXs/UJ_BW.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн в стиле MINI copper от BMW.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Мягкий матрасик для комфортного сна ребёнка с боковой поддержкой спины и ног.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 301,
    sectionId: 3,
    type: 'buggy',
    model: 'easywalkerXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker XS Monaco Apero',
    price: 7950,
    sex: 'girl',
    img1: '../../assets/img/img_product_easywalkerXs/monaco_apero_XS.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/monaco_apero_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/monaco_apero_XS.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн в традиционном спокойном нидерландском стиле.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 302,
    sectionId: 3,
    type: 'buggy',
    model: 'easywalkerXs',
    h1: 'Прогулочная коляска-"книжка" Easywalker XS Berlin Breakfast',
    price: 7950,
    sex: 'boy',
    img1: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн в традиционном спокойном нидерландском стиле.',
    feature2: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature3: 'Складывание и раскладывание коляски происходит одной рукой – максимальный комфорт для путешествий и переноски.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Компактные размеры – подходят под требования ручной клади, поместиться в багажник любого автомобиля или просто на заднем сидении автомобиля.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Вес коляски всего 6 кг., изготовлена из высококачественного и лёгкого алюминия.',
    babyAge: 'С 4 месяцев до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 401,
    sectionId: 4,
    type: 'buggy',
    model: 'miniBuggy',
    h1: 'Прогулочная коляска-"трость" Easywalker MINI Buggy Union Jack Classic',
    price: 8670,
    sex: 'all',
    img1: '../../assets/img/img_product_miniBuggy/uj_classic1.jpg',
    img2: '../../assets/img/img_product_miniBuggy/uj_classic2.jpg',
    img3: '../../assets/img/img_product_miniBuggy/uj_classic3.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн от корпорации BMW в стиле гоночного болида Британии команды MINI cooper.',
    feature2: 'Авторское просторное сиденье от всемирно известной компании BMW с подголовником и боковой поддержкой спины ребёнка.',
    feature3: 'Капор коляски оборудован фиксатором Stay back от случайного закрытия.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Коляска снабжена ручкой для переноски, а также дополнительно ремнём для переноски когда Ваши руки заняты.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Сдвоенные колёса для устойчивости коляски; передние колёса поворотные; фиксация передних колёс.',
    babyAge: 'С 4 месяцев до 4 лет',
    babyWeight: 'До 20 кг',
    foldingType: 'Трость',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},

    {id: 402,
    sectionId: 4,
    type: 'buggy',
    model: 'miniBuggy',
    h1: 'Прогулочная коляска-"трость" Easywalker MINI Buggy Union Jack Vintage',
    price: 8670,
    sex: 'all',
    img1: '../../assets/img/img_product_miniBuggy/uj_vintage1.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн от корпорации BMW в стиле гоночного болида Британии команды MINI cooper.',
    feature2: 'Авторское просторное сиденье от всемирно известной компании BMW с подголовником и боковой поддержкой спины ребёнка.',
    feature3: 'Капор коляски оборудован фиксатором Stay back от случайного закрытия.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Коляска снабжена ручкой для переноски, а также дополнительно ремнём для переноски когда Ваши руки заняты.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Сдвоенные колёса для устойчивости коляски; передние колёса поворотные; фиксация передних колёс.',
    babyAge: 'С 4 месяцев до 4 лет',
    babyWeight: 'До 20 кг',
    foldingType: 'Трость',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},

{id: 403,
    sectionId: 4,
    type: 'buggy',
    model: 'miniBuggy',
    h1: 'Прогулочная коляска-"трость" Easywalker MINI Buggy Milky Jack',
    price: 8670,
    sex: 'all',
    img1: '../../assets/img/img_product_miniBuggy/milky_jack1.jpg',
    img2: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    img3: '../../assets/img/img_product_easywalkerXs/berlin_breakfast_XS.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Дизайн от корпорации BMW в стиле гоночного болида Британии команды MINI cooper.',
    feature2: 'Авторское просторное сиденье от всемирно известной компании BMW с подголовником и боковой поддержкой спины ребёнка.',
    feature3: 'Капор коляски оборудован фиксатором Stay back от случайного закрытия.',
    feature4: 'Аторская амортизация на 4-х колесах от компании BMW, неровности дорог не передаются ребёнку, нет нагрузки на тело и позвоночник.',
    feature5: 'Коляска снабжена ручкой для переноски, а также дополнительно ремнём для переноски когда Ваши руки заняты.',
    feature6: 'Съёмный тент на задней спинке коляски для 100% вентиляции летом и закрытый вариант для прохладной погоды.',
    feature7: 'Сдвоенные колёса для устойчивости коляски; передние колёса поворотные; фиксация передних колёс.',
    babyAge: 'С 4 месяцев до 4 лет',
    babyWeight: 'До 20 кг',
    foldingType: 'Трость',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    removableSoftParts: 'Да',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 501,
    sectionId: 5,
    type: 'stroller',
    model: 'harvey',
    h1: 'Коляска 2в1 Harvey 2.0 голубая',
    price: 25000,
    sex: 'boy',
    img1: '../../assets/img/img_product_harvey/harvey_blue.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Растёт весте с вами и позволяет используя 1 шасси переоборудовать коляску для двух детей (двойни), погодок и снова переоборудовать под 1 ребёнка.',
    feature2: 'Колёса заполнены твёрдой пеной, что позволяет им оставаться прочными в любую погоду и делает коляски максимально устойчивой.',
    feature3: 'Коляска складывается и раскладывается одной рукой, при этом шасси снабжено удобной ручкой для переноски. Сидение для прогулки снимать не обязательно, коляска сложиться вместе с ним.',
    feature4: 'Сидение прогулочного блока устанавливается по ходу движения и против хода движения, снабжено 4-х вариантами наклона спинки, регулировкой подножки в 4-х положениях.',
    feature5: 'Капор прогулочного двойной на 2 секции, снабжён смотровым окошком и москитными вставками для проветривания в жаркую погоду.',
    feature6: 'Все материалы высочайшего качества, очень мягкие и нежные, отталкивают влагу и легко чистятся. Допустима ручная стирка.',
    feature7: 'Коляска Harvey прошла тестирование согласно Европейских стандартов качества и безопасности по системе EN1888.',
    babyAge: 'С 0 до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 502,
    sectionId: 5,
    type: 'stroller',
    model: 'harvey',
    h1: 'Коляска 2в1 Harvey 2.0 розовая',
    price: 25000,
    sex: 'girl',
    img1: '../../assets/img/img_product_harvey/harvey_pink.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Растёт весте с вами и позволяет используя 1 шасси переоборудовать коляску для двух детей (двойни), погодок и снова переоборудовать под 1 ребёнка.',
    feature2: 'Колёса заполнены твёрдой пеной, что позволяет им оставаться прочными в любую погоду и делает коляски максимально устойчивой.',
    feature3: 'Коляска складывается и раскладывается одной рукой, при этом шасси снабжено удобной ручкой для переноски. Сидение для прогулки снимать не обязательно, коляска сложиться вместе с ним.',
    feature4: 'Сидение прогулочного блока устанавливается по ходу движения и против хода движения, снабжено 4-х вариантами наклона спинки, регулировкой подножки в 4-х положениях.',
    feature5: 'Капор прогулочного двойной на 2 секции, снабжён смотровым окошком и москитными вставками для проветривания в жаркую погоду.',
    feature6: 'Все материалы высочайшего качества, очень мягкие и нежные, отталкивают влагу и легко чистятся. Допустима ручная стирка.',
    feature7: 'Коляска Harvey прошла тестирование согласно Европейских стандартов качества и безопасности по системе EN1888.',
    babyAge: 'С 0 до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 503,
    sectionId: 5,
    type: 'stroller',
    model: 'harvey',
    h1: 'Коляска 2в1 Harvey 2.0 черная',
    price: 25000,
    sex: 'all',
    img1: '../../assets/img/img_product_harvey/harvey_black.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Растёт весте с вами и позволяет используя 1 шасси переоборудовать коляску для двух детей (двойни), погодок и снова переоборудовать под 1 ребёнка.',
    feature2: 'Колёса заполнены твёрдой пеной, что позволяет им оставаться прочными в любую погоду и делает коляски максимально устойчивой.',
    feature3: 'Коляска складывается и раскладывается одной рукой, при этом шасси снабжено удобной ручкой для переноски. Сидение для прогулки снимать не обязательно, коляска сложиться вместе с ним.',
    feature4: 'Сидение прогулочного блока устанавливается по ходу движения и против хода движения, снабжено 4-х вариантами наклона спинки, регулировкой подножки в 4-х положениях.',
    feature5: 'Капор прогулочного двойной на 2 секции, снабжён смотровым окошком и москитными вставками для проветривания в жаркую погоду.',
    feature6: 'Все материалы высочайшего качества, очень мягкие и нежные, отталкивают влагу и легко чистятся. Допустима ручная стирка.',
    feature7: 'Коляска Harvey прошла тестирование согласно Европейских стандартов качества и безопасности по системе EN1888.',
    babyAge: 'С 0 до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 601,
    sectionId: 6,
    type: 'stroller',
    model: 'charley',
    h1: 'Коляска 2в1 charley голубая',
    price: 23000,
    sex: 'boy',
    img1: '../../assets/img/img_product_charley/charley_blue.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Самая компактная коляска для новорожденных в мире!',
    feature2: 'Колёса заполнены твёрдой пеной, что позволяет им оставаться прочными в любую погоду и делает коляски максимально устойчивой.',
    feature3: 'Коляска складывается и раскладывается одной рукой, при этом шасси снабжено удобной ручкой для переноски. Сидение для прогулки снимать не обязательно, коляска сложиться вместе с ним.',
    feature4: 'Сидение прогулочного блока устанавливается по ходу движения и против хода движения, снабжено 4-х вариантами наклона спинки, регулировкой подножки в 4-х положениях.',
    feature5: 'Капор прогулочного двойной на 2 секции, снабжён смотровым окошком и москитными вставками для проветривания в жаркую погоду.',
    feature6: 'Все материалы высочайшего качества, очень мягкие и нежные, отталкивают влагу и легко чистятся. Допустима ручная стирка.',
    feature7: 'Коляска Harvey прошла тестирование согласно Европейских стандартов качества и безопасности по системе EN1888.',
    babyAge: 'С 0 до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 602,
    sectionId: 6,
    type: 'stroller',
    model: 'charley',
    h1: 'Коляска 2в1 charley розовая',
    price: 23000,
    sex: 'girl',
    img1: '../../assets/img/img_product_charley/charley_pink.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Самая компактная коляска для новорожденных в мире!',
    feature2: 'Колёса заполнены твёрдой пеной, что позволяет им оставаться прочными в любую погоду и делает коляски максимально устойчивой.',
    feature3: 'Коляска складывается и раскладывается одной рукой, при этом шасси снабжено удобной ручкой для переноски. Сидение для прогулки снимать не обязательно, коляска сложиться вместе с ним.',
    feature4: 'Сидение прогулочного блока устанавливается по ходу движения и против хода движения, снабжено 4-х вариантами наклона спинки, регулировкой подножки в 4-х положениях.',
    feature5: 'Капор прогулочного двойной на 2 секции, снабжён смотровым окошком и москитными вставками для проветривания в жаркую погоду.',
    feature6: 'Все материалы высочайшего качества, очень мягкие и нежные, отталкивают влагу и легко чистятся. Допустима ручная стирка.',
    feature7: 'Коляска Harvey прошла тестирование согласно Европейских стандартов качества и безопасности по системе EN1888.',
    babyAge: 'С 0 до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
    {id: 603,
    sectionId: 6,
    type: 'stroller',
    model: 'charley',
    h1: 'Коляска 2в1 charley серая',
    price: 23000,
    sex: 'all',
    img1: '../../assets/img/img_product_charley/charley_grey.jpg',
    img2: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    img3: '../../assets/img/img_product_disneyXs/Mickey.jpg',
    seoText: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Impedit omnis deleniti cumque rem mollitia similique reprehenderit? Rem deserunt voluptas dicta reprehenderit fugit officia ducimus distinctio inventore similique ipsam praesentium laborum ipsa ullam, temporibus, ex minus aperiam reiciendis aliquam delectus molestias. Inventore esse delectus quas velit veniam distinctio officia neque perferendis placeat recusandae sint fugiat, debitis vel voluptatibus eveniet voluptate nam. Neque cumque iusto quam quo, odio esse ratione architecto ut veniam! Nostrum temporibus tenetur porro commodi odit dicta consequatur sequi, ducimus dignissimos rem molestias labore dolorem voluptate quos reprehenderit quas placeat voluptatem ratione amet optio dolor ex a. Suscipit commodi quod perspiciatis reprehenderit nulla asperiores, sint optio. Laborum ex eius excepturi nesciunt quis. Voluptate vero ducimus ratione. Expedita, magni quidem! Veniam laboriosam nulla excepturi architecto modi nisi deleniti quas? Quidem nulla beatae id voluptas recusandae consequuntur repudiandae neque facere atque qui labore, temporibus sit deleniti reprehenderit a tempora maiores fuga.',
    feature1: 'Самая компактная коляска для новорожденных в мире!',
    feature2: 'Колёса заполнены твёрдой пеной, что позволяет им оставаться прочными в любую погоду и делает коляски максимально устойчивой.',
    feature3: 'Коляска складывается и раскладывается одной рукой, при этом шасси снабжено удобной ручкой для переноски. Сидение для прогулки снимать не обязательно, коляска сложиться вместе с ним.',
    feature4: 'Сидение прогулочного блока устанавливается по ходу движения и против хода движения, снабжено 4-х вариантами наклона спинки, регулировкой подножки в 4-х положениях.',
    feature5: 'Капор прогулочного двойной на 2 секции, снабжён смотровым окошком и москитными вставками для проветривания в жаркую погоду.',
    feature6: 'Все материалы высочайшего качества, очень мягкие и нежные, отталкивают влагу и легко чистятся. Допустима ручная стирка.',
    feature7: 'Коляска Harvey прошла тестирование согласно Европейских стандартов качества и безопасности по системе EN1888.',
    babyAge: 'С 0 до 3 лет',
    babyWeight: 'До 15 кг',
    foldingType: 'Книжка',
    backrestAdjustment: 'Есть',
    seatBelts: 'Есть, 5-ти точечные',
    basketForThings: 'Да, до 5 кг.',
    quantity: 1
},
]


