export class ProductTemplate {
    id: number;
    sectionId: number;
    type: string;
    model: string;
    h1: string;
    price: number;
    sex: string;
    img1: string;
    img2?: string;
    img3?: string;
    seoText: string;
    feature1: string;
    feature2: string;
    feature3: string;
    feature4: string;
    feature5: string;
    feature6: string;
    feature7: string;
    babyAge?: string;
    babyWeight?: string;
    foldingType?: string;
    backrestAdjustment?: string;
    seatBelts?: string;
    removableSoftParts?: string;
    basketForThings?: string;
    quantity: number;
    totalItem?: number;
}