import { SectionTemplate } from './section-template';

export const SECTION: SectionTemplate[] = [
    {
        id: 1,
        titleMenu: '"Книжки" Disney',
        type: 'buggy',
        model: 'disneyXS',
        backgroundImageMainScreen: 'assets/img/img_section/section_disney.PNG',
        h1: 'Прогулочные коляски-книжки Easywalker Disney XS',
        iframeSrc: 'https://www.youtube.com/embed/97L8dk44uJs',
        ulLi1: 'Складываются и раскладываются одним движением.',
        ulLi2: 'Вес 6 кг.',
        ulLi3: 'Сответствуют параметрам ручной клади.',
        ulLi4: 'Дизайн и брендирование от всемирно известной компании Disney.',
        ulLi5: 'В комплект входят: шасси, сидение + тент, дождевик, бампер, корзина для покупок. ',
        h2: 'Выберите свою Easywalker Disney XS'
    },
    {
        id: 2,
        titleMenu: '"Книжки" Mini',
        type: 'buggy',
        model: 'miniXs',
        backgroundImageMainScreen: '../../assets/img/img_section/section_mini.PNG',
        h1: 'Прогулочные коляски-книжки Easywalker MINI XS',
        iframeSrc: 'https://www.youtube.com/embed/y3FTyX2OyEw',
        ulLi1: 'Складываются и раскладываются одним движением.',
        ulLi2: 'Вес 6 кг.',
        ulLi3: 'Сответствуют параметрам ручной клади.',
        ulLi4: 'Дизайн и брендирование в стиле MINI Cooper.',
        ulLi5: 'В комплект входят: шасси, сидение + тент, дождевик, бампер, корзина для покупок. ',
        h2: 'Выберите свою Easywalker MINI XS'
    },
    {
        id: 3,
        titleMenu: '"Книжки" Easywalker',
        type: 'buggy',
        model: 'easywalkerXs',
        backgroundImageMainScreen: '../../assets/img/img_section/section_ew.PNG',
        h1: 'Прогулочные коляски-книжки Easywalker XS',
        iframeSrc: 'https://www.youtube.com/embed/gSz8z3_WA5E',
        ulLi1: 'Складываются и раскладываются одним движением.',
        ulLi2: 'Вес 6 кг.',
        ulLi3: 'Сответствуют параметрам ручной клади.',
        ulLi4: 'Дизайн и брендирование от Easywalker.',
        ulLi5: 'В комплект входят: шасси, сидение + тент, дождевик, бампер, корзина для покупок. ',
        h2: 'Выберите свою Easywalker XS'
    },
    {
        id: 4,
        titleMenu: '"Трости" Mini',
        type: 'buggy',
        model: 'miniBuggy',
        backgroundImageMainScreen: '../../assets/img/img_section/section_mini.PNG',
        h1: 'Прогулочные коляски-трости MINI',
        iframeSrc: 'https://www.youtube.com/embed/o7aWuCG_qso',
        ulLi1: 'Складываются и раскладываются одним движением.',
        ulLi2: 'Вес 6 кг.',
        ulLi3: 'Сответствуют параметрам ручной клади.',
        ulLi4: 'Дизайн и брендирование от Easywalker.',
        ulLi5: 'В комплект входят: шасси, сидение + тент, дождевик, бампер, корзина для покупок. ',
        h2: 'Выберите свою Easywalker XS'
    },
    {
        id: 5,
        titleMenu: 'Harvey 2.0',
        type: 'stroller',
        model: 'harvey',
        backgroundImageMainScreen: '../../assets/img/img_section/section_harvey.PNG',
        h1: 'Коляски 2в1 для новорожденных Harvey 2.0',
        iframeSrc: 'https://www.youtube.com/embed/LBwIQjZFs_w',
        ulLi1: 'Растёт весте с Вами и позволяет используя 1 шасси переоборудовать коляску для двух детей (двойни), погодок и снова переоборудовать под 1 ребёнка.',
        ulLi2: 'Сидение прогулочного блока устанавливается по ходу движения и против хода движения, снабжено 4-х вариантами наклона спинки.',
        ulLi3: ' Прогулочный блок может использоваться с полугода и выдерживает 15 кг. нагрузку.',
        ulLi4: 'Вес шасси коляски всего 8 кг., при таком функционале и возможностях это лучшее решение на рынке колясок для новорожденных.',
        ulLi5: 'Шасси, люлька, полноценный матрасик в люльку, дождевик для люльки, прогулочный блок с двойным капором, бампер прогулочного блока, адаптеры высоты, корзина для покупок.',
        h2: 'Выберите свою Harvey 2.0'
    },
    {
        id: 6,
        titleMenu: 'Charley',
        type: 'stroller',
        model: 'charley',
        backgroundImageMainScreen: '../../assets/img/img_section/section_charley.PNG',
        h1: 'Коляски 2в1 для новорожденных Charley',
        iframeSrc: 'https://www.youtube.com/embed/giMv5KhdxF8',
        ulLi1: 'Самая компактная коляска для новорожденных в мире!',
        ulLi2: 'Все материалы высочайшего качества, очень мягкие и нежные, отталкивают влагу и легко чистятся. Допустима ручная стирка.',
        ulLi3: 'Капор прогулочного двойной на 2 секции, снабжён смотровым окошком и москитными вставками для проветривания в жаркую погоду.',
        ulLi4: 'Прогулочный блок может использоваться с полугода и выдерживает 15 кг. нагрузку.',
        ulLi5: 'Шасси, люлька, полноценный матрасик в люльку, дождевик для люльки, прогулочный блок с двойным капором, бампер прогулочного блока, адаптеры высоты, корзина для покупок.',
        h2: 'Выберите свою Charley'
    }
]